spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/member
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  h2:
    console:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
      
springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
